Repository knative/serving-operator, pull requests merged in 2019-09, with the labels that each got.

#158 golang format tools
  pkg/reconciler/knativeserving/controller.go
  pkg/reconciler/knativeserving/knativeserving_controller.go
Labels: approved, cla: yes, lgtm, ok-to-test, size/S

#159 Only delete shared resources when last KS is deleted
  pkg/reconciler/knativeserving/controller.go
  pkg/reconciler/knativeserving/knativeserving_controller.go
  test/cleanup.go
  test/clients.go
  test/e2e/e2e.go
  test/e2e/knativeservingdeployment_test.go
Labels: approved, cla: yes, lgtm, size/M

#166 Clean up logging a bit and remove last bit of controller-runtime
  Gopkg.lock
  Gopkg.toml
  pkg/reconciler/knativeserving/common/config_maps.go
  pkg/reconciler/knativeserving/common/extensions.go
  pkg/reconciler/knativeserving/common/gateway.go
  pkg/reconciler/knativeserving/common/gateway_test.go
  pkg/reconciler/knativeserving/common/images.go
  pkg/reconciler/knativeserving/common/images_test.go
  pkg/reconciler/knativeserving/knativeserving_controller.go
  pkg/reconciler/knativeserving/minikube/minikube.go
  vendor/sigs.k8s.io/controller-runtime/LICENSE
  vendor/sigs.k8s.io/controller-runtime/pkg/runtime/log/deleg.go
  vendor/sigs.k8s.io/controller-runtime/pkg/runtime/log/kube_helpers.go
  vendor/sigs.k8s.io/controller-runtime/pkg/runtime/log/log.go
  vendor/sigs.k8s.io/controller-runtime/pkg/runtime/log/null.go
Labels: approved, cla: yes, lgtm, size/XL

#167 golang format tools
  test/e2e/knativeservingdeployment_test.go
Labels: approved, cla: yes, lgtm, ok-to-test, size/XS

#168 Adding support for imagePullSecrets
  config/crds/serving_v1alpha1_knativeserving_crd.yaml
  pkg/apis/serving/v1alpha1/knativeserving_types.go
  pkg/apis/serving/v1alpha1/zz_generated.deepcopy.go
  pkg/reconciler/knativeserving/common/gateway_test.go
  pkg/reconciler/knativeserving/common/images.go
  pkg/reconciler/knativeserving/common/images_test.go
Labels: approved, cla: yes, lgtm, size/L

#169 golang format tools
  pkg/reconciler/knativeserving/common/images_test.go
Labels: approved, cla: yes, lgtm, ok-to-test, size/S

#173 Add trace for generate-yaml to debug failure
  hack/generate-yamls.sh
Labels: approved, cla: yes, lgtm, size/XS

#174 Fix generate-yamls error by Ignoring grep error
  hack/generate-yamls.sh
Labels: approved, cla: yes, lgtm, size/XS

#176 [Release]Cherry pick 0fefbb9 for fixing generate-yamls
  hack/generate-yamls.sh
Labels: approved, cla: yes, lgtm, size/XS

#177 [Release]Cherry pick 8a0703a for adding trace in generate-yamls
  hack/generate-yamls.sh
Labels: approved, cla: yes, lgtm, size/XS

#178 Additional tests for resource deletion and update
  test/e2e/knativeservingdeployment_test.go
Labels: approved, cla: yes, lgtm, size/L

#179 devstats was removed, no need to clean it up
  hack/update-deps.sh
Labels: approved, cla: yes, lgtm, size/XS

#150 Make sure the pod of the operator is running, before test case is running
  test/e2e-common.sh
Labels: approved, cla: yes, lgtm, size/S

#180 Set the default GroupVersionKind for KnativeServing
  pkg/apis/serving/v1alpha1/knativeserving_lifecycle.go
  pkg/apis/serving/v1alpha1/knativeserving_lifecycle_test.go
  pkg/apis/serving/v1alpha1/register.go
  pkg/apis/serving/v1alpha1/register_test.go
  pkg/reconciler/knativeserving/knativeserving_controller.go
Labels: approved, cla: yes, lgtm, size/M

#182 Skip the namespace check for integration test
  test/e2e/knativeservingdeployment_test.go
Labels: approved, cla: yes, lgtm, size/XS

#183 Comment extra YAML listing until they're available
  hack/generate-yamls.sh
Labels: approved, cla: yes, lgtm, size/XS
