Repository knative/serving-operator, pull requests merged in 2019-12, with the labels that each got.

#238 Update to latest manifestival
  Gopkg.lock
  Gopkg.toml
  vendor/github.com/jcrossley3/manifestival/manifestival.go
  vendor/github.com/jcrossley3/manifestival/transform.go
  vendor/github.com/jcrossley3/manifestival/yaml.go
Labels: approved, cla: yes, lgtm, size/M

#229 Propagating configured imagePullSecrets to the Image
  pkg/reconciler/knativeserving/common/images.go
  pkg/reconciler/knativeserving/common/images_test.go
Labels: approved, cla: yes, lgtm, size/M

#235 Delete manifest resources in a finalizer
  pkg/reconciler/knativeserving/knativeserving_controller.go
  test/e2e/knativeservingdeployment_test.go
Labels: approved, cla: yes, lgtm, size/M

#236 Add a "DependenciesInstalled" condition that defaults to true
  pkg/apis/serving/v1alpha1/knativeserving_lifecycle.go
  pkg/apis/serving/v1alpha1/knativeserving_lifecycle_test.go
  pkg/apis/serving/v1alpha1/knativeserving_types.go
Labels: approved, cla: yes, lgtm, size/M

#223 Letting flags be changed from outside
  .gitignore
  hack/update-deps.sh
  test/e2e_flags.go
Labels: approved, cla: yes, lgtm, ok-to-test, size/S

#233 Add metrics about KnativeServing CR edits
  pkg/reconciler/knativeserving/controller.go
  pkg/reconciler/knativeserving/knativeserving_controller.go
  pkg/reconciler/reconciler.go
  pkg/reconciler/reconciler_test.go
  pkg/reconciler/stats_reporter.go
  pkg/reconciler/stats_reporter_test.go
Labels: approved, cla: yes, lgtm, size/L

#244 golang format tools
  pkg/reconciler/knativeserving/knativeserving_controller.go
Labels: approved, cla: yes, lgtm, size/XS

#243 Update to latest manifestival to apply strategic merge patches to its resources.
  Gopkg.lock
  pkg/reconciler/knativeserving/common/certs.go
  pkg/reconciler/knativeserving/common/images.go
  third_party/VENDOR-LICENSE
  vendor/github.com/jcrossley3/manifestival/manifestival.go
  vendor/github.com/jcrossley3/manifestival/patch/patch.go
  vendor/k8s.io/apimachinery/pkg/util/jsonmergepatch/patch.go
Labels: approved, cla: yes, lgtm, size/L

#246 Updates to ship 0.11.0 releae of knative-serving
  cmd/manager/kodata/knative-serving/0.11.0.yaml
  version/version.go
Labels: approved, cla: yes, lgtm, size/L
