Repository knative/serving-operator, pull requests merged in 2019-10, with the labels that each got.

#184 Removing logging override examples from config-logging.yaml
  config/config-logging.yaml
Labels: approved, cla: yes, lgtm, size/S

#186 Move the CRD to the directory config
  README.md
  config/300-serving-v1alpha1-knativeserving-crd.yaml
  test/e2e-common.sh
Labels: approved, cla: yes, lgtm, size/S

#189 Update the license of third party and symlinking to licenses
  cmd/manager/kodata/HEAD
  cmd/manager/kodata/LICENSE
  cmd/manager/kodata/VENDOR-LICENSE
  cmd/manager/kodata/refs
  hack/update-deps.sh
  third_party/VENDOR-LICENSE
Labels: approved, cla: yes, lgtm, size/XXL

#191 Add a new script to test the latest generated manifest of knative serving
  test/config
  test/config/0.8.0.yaml
  test/e2e-common.sh
  test/e2e-tests-latest-serving.sh
  test/e2e-tests.sh
Labels: approved, cla: yes, lgtm, size/L

#198 Move to operator.knative.dev API_Group
  README.md
  config/300-serving-v1alpha1-knativeserving-crd.yaml
  config/role.yaml
  pkg/apis/serving/v1alpha1/doc.go
  pkg/apis/serving/v1alpha1/register.go
  pkg/client/clientset/versioned/clientset.go
  pkg/client/clientset/versioned/fake/clientset_generated.go
  pkg/client/clientset/versioned/fake/register.go
  pkg/client/clientset/versioned/scheme/register.go
  pkg/client/clientset/versioned/typed/serving/v1alpha1/fake/fake_knativeserving.go
  pkg/client/clientset/versioned/typed/serving/v1alpha1/fake/fake_serving_client.go
  pkg/client/clientset/versioned/typed/serving/v1alpha1/knativeserving.go
  pkg/client/clientset/versioned/typed/serving/v1alpha1/serving_client.go
  pkg/client/informers/externalversions/factory.go
  pkg/client/informers/externalversions/generic.go
  pkg/client/informers/externalversions/serving/interface.go
  pkg/client/informers/externalversions/serving/v1alpha1/knativeserving.go
  pkg/client/injection/informers/serving/v1alpha1/knativeserving/fake/fake.go
  pkg/client/injection/informers/serving/v1alpha1/knativeserving/knativeserving.go
  pkg/reconciler/knativeserving/knativeserving_controller.go
  test/clients.go
Labels: approved, cla: yes, lgtm, size/L

#199 Update to 0.10 release
  cmd/manager/kodata/knative-serving/0.10.0.yaml
  version/version.go
Labels: approved, cla: yes, lgtm, size/XL
