Repository knative/serving-operator, pull requests merged in 2019-11, with the labels that each got.

#209 In the README, refer to a nightly build instead of the openshift fork
  README.md
Labels: approved, cla: yes, lgtm, size/S

#211 Clean up the [un]structured conversions a bit
  pkg/reconciler/knativeserving/common/gateway_test.go
  pkg/reconciler/knativeserving/common/images.go
  pkg/reconciler/knativeserving/common/images_test.go
Labels: approved, cla: yes, lgtm, size/M

#213 Applying a released version of the operator
  README.md
Labels: approved, cla: yes, lgtm, size/S

#204 Add the marker of the latest commit ID for better debugging
  test/e2e-tests-latest-serving.sh
Labels: approved, cla: yes, lgtm, size/XS

#212 We need to fail the install if any transforms error
  pkg/reconciler/knativeserving/knativeserving_controller.go
Labels: approved, cla: yes, lgtm, size/XS

#217 Format markdown
  README.md
Labels: approved, cla: yes, lgtm, size/S

#218 Update vendor/knative.dev/test-infra
  Gopkg.lock
  vendor/knative.dev/test-infra/scripts/e2e-tests.sh
  vendor/knative.dev/test-infra/scripts/library.sh
  vendor/knative.dev/test-infra/scripts/performance-tests.sh
  vendor/knative.dev/test-infra/scripts/release.sh
Labels: approved, cla: yes, lgtm, size/M

#219 Configure controller to trust registries with self-signed certs
  config/300-serving-v1alpha1-knativeserving-crd.yaml
  pkg/apis/serving/v1alpha1/knativeserving_types.go
  pkg/apis/serving/v1alpha1/zz_generated.deepcopy.go
  pkg/reconciler/knativeserving/common/certs.go
  pkg/reconciler/knativeserving/common/certs_test.go
  pkg/reconciler/knativeserving/common/extensions.go
Labels: approved, cla: yes, lgtm, size/L

#216 Add metrics port to operator
  cmd/manager/main.go
  config/operator.yaml
Labels: approved, cla: yes, lgtm, size/XS

#224 Add test for version consistency
  version/version_test.go
Labels: approved, cla: yes, lgtm, ok-to-test, size/M

#228 golang format tools
  version/version_test.go
Labels: approved, cla: yes, lgtm, size/XS
