Repository knative/serving-operator, pull requests merged in 2019-06, with the labels that each got.

#19 Format markdown
  README.md
Labels: lgtm, size/XS

#18 Add the ko support to build the image for the operator
  README.md
  config/crds/serving_v1alpha1_knativeserving_cr.yaml
  config/crds/serving_v1alpha1_knativeserving_crd.yaml
  config/olm-catalog/knative-serving-operator/0.5.2/knative-serving-operator.v0.5.2.clusterserviceversion.yaml
  config/olm-catalog/knative-serving-operator/0.5.2/serving_v1alpha1_install_crd.yaml
  config/olm-catalog/knative-serving-operator/0.6.0/knative-serving-operator.v0.6.0.clusterserviceversion.yaml
  config/olm-catalog/knative-serving-operator/0.6.0/serving_v1alpha1_knativeserving_crd.yaml
  config/olm-catalog/knative-serving-operator/knative-serving-operator.package.yaml
  config/operator.yaml
  config/resources/knative-serving-0.6.0.yaml
  config/resources/maistra/maistra-controlplane-0.10.0.yaml
  config/resources/maistra/maistra-operator-0.10.yaml
  config/resources/openshift-ingress/openshift-ingress-0.0.4.yaml
  config/role.yaml
  config/role_binding.yaml
  config/service_account.yaml
  deploy
  hack/generate-yamls.sh
  hack/release.md
  hack/release.sh
  test/e2e-common.sh
  test/e2e/knative_serving_test.go
  test/e2e/main_test.go
Labels: approved, lgtm, size/L

#29 Temporarily stop waiting for knative-serving until tests work
  test/e2e-tests.sh
Labels: approved, lgtm, size/XS

#22 Remove comand from operator container
  config/operator.yaml
Labels: approved, lgtm, size/XS

#34 Fix OWNERS entry for k4leung4
  OWNERS
Labels: approved, lgtm, size/XS

#33 Format markdown
  README.md
  hack/release.md
Labels: approved, lgtm, ok-to-test, size/M

#26 Fix the failures in PR builds
  .osdk-scorecard.yaml
  hack/catalog.sh
  hack/generate-yamls.sh
  pkg/apis/serving/v1alpha1/zz_generated.defaults.go
  pkg/apis/serving/v1alpha1/zz_generated.openapi.go
  pkg/controller/knativeserving/knativeserving_controller.go
  pkg/controller/knativeserving/openshift/openshift.go
Labels: approved, lgtm, size/M

#23 Ko datadir
  Gopkg.lock
  cmd/manager/kodata/knative-serving-0.6.0.yaml
  cmd/manager/kodata/serving_v1alpha1_knativeserving_cr.yaml
  pkg/controller/knativeserving/knativeserving_controller.go
  vendor/github.com/jcrossley3/manifestival/yaml.go
Labels: approved, lgtm, size/S

#37 Use KO_DATA_PATH for custom resource
  pkg/controller/knativeserving/knativeserving_controller.go
Labels: approved, lgtm, size/XS

#31 Re-enable integration tests
  test/e2e-tests.sh
Labels: approved, lgtm, size/XS
