Repository knative/serving-operator, pull requests merged in 2019-07, with the labels that each got.

#38 Increase logging for knativeserving controller
  pkg/controller/knativeserving/knativeserving_controller.go
Labels: approved, lgtm, size/XS

#41 Address receiver name lint error
  pkg/apis/serving/v1alpha1/knativeserving_lifecycle.go
Labels: approved, lgtm, size/XS

#45 Move knative release yaml to kodata.
  cmd/manager/kodata/knative-serving-0.6.0.yaml
  cmd/manager/kodata/knative-serving/0.6.0.yaml
  pkg/controller/knativeserving/knativeserving_controller.go
Labels: approved, lgtm, size/XS

#44 Update operator to install knative serving 0.7.0
  cmd/manager/kodata/knative-serving/0.7.0.yaml
  version/version.go
Labels: approved, lgtm, size/L

#20 Add ability to update the image and tag of knative serving images
  Gopkg.lock
  Gopkg.toml
  config/crds/serving_v1alpha1_knativeserving_crd.yaml
  pkg/apis/serving/v1alpha1/knativeserving_types.go
  pkg/controller/knativeserving/common/config_maps.go
  pkg/controller/knativeserving/common/extensions.go
  pkg/controller/knativeserving/common/images.go
  pkg/controller/knativeserving/common/images_test.go
  pkg/controller/knativeserving/knativeserving_controller.go
  vendor/knative.dev/caching/LICENSE
  vendor/knative.dev/caching/pkg/apis/caching/register.go
  vendor/knative.dev/caching/pkg/apis/caching/v1alpha1/doc.go
  vendor/knative.dev/caching/pkg/apis/caching/v1alpha1/image_defaults.go
  vendor/knative.dev/caching/pkg/apis/caching/v1alpha1/image_types.go
  vendor/knative.dev/caching/pkg/apis/caching/v1alpha1/image_validation.go
  vendor/knative.dev/caching/pkg/apis/caching/v1alpha1/register.go
  vendor/knative.dev/caching/pkg/apis/caching/v1alpha1/zz_generated.deepcopy.go
Labels: approved, lgtm, size/XXL

#53 Add trshafer as approver
  OWNERS
Labels: approved, lgtm, size/XS

#54 Add houshengbo as approver
  OWNERS
Labels: approved, lgtm, size/XS

#48 A simple script to run the operator locally
  README.md
  hack/run-local.sh
Labels: approved, lgtm, size/M

#55 Update default CR with knative-serving namespace.
  config/crds/serving_v1alpha1_knativeserving_cr.yaml
Labels: approved, lgtm, size/XS

#58 Revert "Update default CR with knative-serving namespace. (#55)"
  config/crds/serving_v1alpha1_knativeserving_cr.yaml
Labels: approved, lgtm, size/XS

#62 Format markdown
  README.md
Labels: approved, lgtm, ok-to-test, size/XS

#67 Relocate the transformation logic to each respective common library.
  pkg/controller/knativeserving/common/config_maps.go
  pkg/controller/knativeserving/common/extensions.go
  pkg/controller/knativeserving/common/images.go
  pkg/controller/knativeserving/common/images_test.go
Labels: approved, cla: yes, lgtm, size/L

#64 Add ability to update the KnativeIngressGateway istio selector
  config/crds/serving_v1alpha1_knativeserving_crd.yaml
  pkg/apis/serving/v1alpha1/knativeserving_types.go
  pkg/controller/knativeserving/common/extensions.go
  pkg/controller/knativeserving/common/gateway.go
  pkg/controller/knativeserving/common/gateway_test.go
Labels: approved, cla: yes, lgtm, size/L

#69 Rename the directory controller into reconciler
  cmd/manager/main.go
  pkg/reconciler/add_knativeserving.go
  pkg/reconciler/controller.go
  pkg/reconciler/knativeserving/add_minikube.go
  pkg/reconciler/knativeserving/add_openshift.go
  pkg/reconciler/knativeserving/common/config_maps.go
  pkg/reconciler/knativeserving/common/extensions.go
  pkg/reconciler/knativeserving/common/gateway.go
  pkg/reconciler/knativeserving/common/gateway_test.go
  pkg/reconciler/knativeserving/common/images.go
  pkg/reconciler/knativeserving/common/images_test.go
  pkg/reconciler/knativeserving/knativeserving_controller.go
  pkg/reconciler/knativeserving/minikube/minikube.go
  pkg/reconciler/knativeserving/openshift/openshift.go
Labels: approved, cla: yes, lgtm, size/S

#68 Migrate serving operator to use knative.dev/serving-operator import path
  README.md
  cmd/manager/main.go
  config/operator.yaml
  hack/update-codegen.sh
  pkg/apis/addtoscheme_serving_v1alpha1.go
  pkg/apis/serving/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/serving/v1alpha1/zz_generated.openapi.go
  pkg/client/clientset/versioned/clientset.go
  pkg/client/clientset/versioned/fake/clientset_generated.go
  pkg/client/clientset/versioned/fake/register.go
  pkg/client/clientset/versioned/scheme/register.go
  pkg/client/clientset/versioned/typed/serving/v1alpha1/fake/fake_knativeserving.go
  pkg/client/clientset/versioned/typed/serving/v1alpha1/fake/fake_serving_client.go
  pkg/client/clientset/versioned/typed/serving/v1alpha1/knativeserving.go
  pkg/client/clientset/versioned/typed/serving/v1alpha1/serving_client.go
  pkg/client/informers/externalversions/factory.go
  pkg/client/informers/externalversions/generic.go
  pkg/client/informers/externalversions/internalinterfaces/factory_interfaces.go
  pkg/client/informers/externalversions/serving/interface.go
  pkg/client/informers/externalversions/serving/v1alpha1/interface.go
  pkg/client/informers/externalversions/serving/v1alpha1/knativeserving.go
  pkg/client/injection/client/client.go
  pkg/client/injection/client/fake/fake.go
  pkg/client/injection/informers/serving/factory/fake/fake.go
  pkg/client/injection/informers/serving/factory/servingfactory.go
  pkg/client/injection/informers/serving/v1alpha1/knativeserving/fake/fake.go
  pkg/client/injection/informers/serving/v1alpha1/knativeserving/knativeserving.go
  pkg/client/listers/serving/v1alpha1/knativeserving.go
  pkg/reconciler/add_knativeserving.go
  pkg/reconciler/knativeserving/add_minikube.go
  pkg/reconciler/knativeserving/add_openshift.go
  pkg/reconciler/knativeserving/common/config_maps.go
  pkg/reconciler/knativeserving/common/extensions.go
  pkg/reconciler/knativeserving/common/gateway.go
  pkg/reconciler/knativeserving/common/gateway_test.go
  pkg/reconciler/knativeserving/common/images.go
  pkg/reconciler/knativeserving/common/images_test.go
  pkg/reconciler/knativeserving/knativeserving_controller.go
  pkg/reconciler/knativeserving/minikube/minikube.go
  pkg/reconciler/knativeserving/openshift/openshift.go
Labels: approved, cla: yes, lgtm, size/L

#76 golang format tools
  pkg/reconciler/knativeserving/common/config_maps.go
  pkg/reconciler/knativeserving/common/extensions.go
  pkg/reconciler/knativeserving/common/gateway.go
  pkg/reconciler/knativeserving/common/gateway_test.go
  pkg/reconciler/knativeserving/common/images.go
  pkg/reconciler/knativeserving/common/images_test.go
  pkg/reconciler/knativeserving/minikube/minikube.go
Labels: approved, cla: yes, lgtm, ok-to-test, size/S

#80 YAMLS_TO_PUBLISH is deprecated, use ARTIFACTS_TO_PUBLISH
  hack/release.sh
Labels: approved, cla: yes, lgtm, size/XS

#78 Access the resources with kubeclient and dynamicclient
  cmd/manager/main.go
  pkg/reconciler/controller.go
  pkg/reconciler/knativeserving/common/extensions.go
  pkg/reconciler/knativeserving/knativeserving_controller.go
  pkg/reconciler/knativeserving/minikube/minikube.go
  pkg/reconciler/knativeserving/openshift/openshift.go
Labels: approved, cla: yes, lgtm, size/M

#91 golang format tools
  pkg/reconciler/knativeserving/knativeserving_controller.go
  pkg/reconciler/knativeserving/minikube/minikube.go
  pkg/reconciler/knativeserving/openshift/openshift.go
Labels: approved, cla: yes, lgtm, ok-to-test, size/M

#86 Clarify installation instructions
  README.md
Labels: approved, cla: yes, lgtm, size/M

#96 Use knative.dev/test-infra
  Gopkg.lock
  Gopkg.toml
  hack/release.sh
  hack/update-codegen.sh
  hack/update-deps.sh
  test/e2e-common.sh
  test/presubmit-tests.sh
  vendor/knative.dev/test-infra/LICENSE
  vendor/knative.dev/test-infra/scripts/README.md
  vendor/knative.dev/test-infra/scripts/dummy.go
  vendor/knative.dev/test-infra/scripts/e2e-tests.sh
  vendor/knative.dev/test-infra/scripts/library.sh
  vendor/knative.dev/test-infra/scripts/markdown-link-check-config.rc
  vendor/knative.dev/test-infra/scripts/markdown-lint-config.rc
  vendor/knative.dev/test-infra/scripts/presubmit-tests.sh
  vendor/knative.dev/test-infra/scripts/release.sh
  vendor/knative.dev/test-infra/tools/dep-collector/README.md
  vendor/knative.dev/test-infra/tools/dep-collector/imports.go
  vendor/knative.dev/test-infra/tools/dep-collector/licenses.go
  vendor/knative.dev/test-infra/tools/dep-collector/main.go
Labels: approved, cla: yes, lgtm, size/M
