Repository knative/serving-operator, pull requests merged in 2019-08, with the labels that each got.

#100 Remove 'WATCH_NAMESPACE' functionality.
  Gopkg.lock
  cmd/manager/main.go
  config/operator.yaml
  hack/run-local.sh
Labels: approved, cla: yes, lgtm, size/S

#103 Add a pull-request template so we almost always automatically run /lint.
  .github/pull-request-template.md
Labels: approved, cla: yes, lgtm, size/S

#102 Format markdown
  README.md
Labels: approved, cla: yes, lgtm, ok-to-test, size/M

#85 Point release documentation to knative/test-infra
  hack/release.md
  hack/release.sh
Labels: approved, cla: yes, lgtm, size/L

#107 golang format tools
  test/clients.go
  test/crd.go
  test/resources/knativeserving.go
Labels: approved, cla: yes, lgtm, ok-to-test, size/S

#101 Remove most of the operator-sdk specific functionality.
  Gopkg.lock
  cmd/manager/main.go
  vendor/github.com/coreos/prometheus-operator/LICENSE
  vendor/github.com/coreos/prometheus-operator/NOTICE
  vendor/github.com/coreos/prometheus-operator/pkg/apis/monitoring/register.go
  vendor/github.com/coreos/prometheus-operator/pkg/apis/monitoring/v1/crd_kinds.go
  vendor/github.com/coreos/prometheus-operator/pkg/apis/monitoring/v1/doc.go
  vendor/github.com/coreos/prometheus-operator/pkg/apis/monitoring/v1/openapi_generated.go
  vendor/github.com/coreos/prometheus-operator/pkg/apis/monitoring/v1/register.go
  vendor/github.com/coreos/prometheus-operator/pkg/apis/monitoring/v1/types.go
  vendor/github.com/coreos/prometheus-operator/pkg/apis/monitoring/v1/zz_generated.deepcopy.go
  vendor/github.com/coreos/prometheus-operator/pkg/client/versioned/scheme/doc.go
  vendor/github.com/coreos/prometheus-operator/pkg/client/versioned/scheme/register.go
  vendor/github.com/coreos/prometheus-operator/pkg/client/versioned/typed/monitoring/v1/alertmanager.go
  vendor/github.com/coreos/prometheus-operator/pkg/client/versioned/typed/monitoring/v1/doc.go
  vendor/github.com/coreos/prometheus-operator/pkg/client/versioned/typed/monitoring/v1/generated_expansion.go
  vendor/github.com/coreos/prometheus-operator/pkg/client/versioned/typed/monitoring/v1/monitoring_client.go
  vendor/github.com/coreos/prometheus-operator/pkg/client/versioned/typed/monitoring/v1/prometheus.go
  vendor/github.com/coreos/prometheus-operator/pkg/client/versioned/typed/monitoring/v1/prometheusrule.go
  vendor/github.com/coreos/prometheus-operator/pkg/client/versioned/typed/monitoring/v1/servicemonitor.go
  vendor/github.com/operator-framework/operator-sdk/pkg/k8sutil/constants.go
  vendor/github.com/operator-framework/operator-sdk/pkg/k8sutil/k8sutil.go
  vendor/github.com/operator-framework/operator-sdk/pkg/leader/doc.go
  vendor/github.com/operator-framework/operator-sdk/pkg/leader/leader.go
  vendor/github.com/operator-framework/operator-sdk/pkg/log/zap/flags.go
  vendor/github.com/operator-framework/operator-sdk/pkg/log/zap/logger.go
  vendor/github.com/operator-framework/operator-sdk/pkg/metrics/metrics.go
  vendor/github.com/operator-framework/operator-sdk/pkg/metrics/service-monitor.go
  vendor/github.com/operator-framework/operator-sdk/version/version.go
  vendor/golang.org/x/tools/internal/gopathwalk/walk.go
  vendor/golang.org/x/tools/internal/imports/fix.go
  vendor/golang.org/x/tools/internal/imports/imports.go
  vendor/knative.dev/pkg/Gopkg.lock
  vendor/knative.dev/pkg/test/vegeta/pacers/combined_pacer.go
  vendor/knative.dev/pkg/test/vegeta/pacers/steady_up_pacer.go
Labels: approved, cla: yes, lgtm, size/XXL

#106 Relax name[space] constraints
  pkg/reconciler/knativeserving/knativeserving_controller.go
Labels: approved, cla: yes, lgtm, size/S

#111 Remove short-circuiting installation logic if we're in an installing state.
  pkg/reconciler/knativeserving/knativeserving_controller.go
Labels: approved, cla: yes, lgtm, size/XS

#110 Remove all references to OLM.
  .osdk-scorecard.yaml
  README.md
  build/Dockerfile
  build/bin/entrypoint
  build/bin/user_setup
  config/olm-catalog/knative-serving-operator/0.5.2/knative-serving-operator.v0.5.2.clusterserviceversion.yaml
  config/olm-catalog/knative-serving-operator/0.5.2/serving_v1alpha1_install_crd.yaml
  config/olm-catalog/knative-serving-operator/0.6.0/knative-serving-operator.v0.6.0.clusterserviceversion.yaml
  config/olm-catalog/knative-serving-operator/0.6.0/serving_v1alpha1_knativeserving_crd.yaml
  config/olm-catalog/knative-serving-operator/knative-serving-operator.package.yaml
  deploy
  hack/catalog.sh
  hack/publish-ci-images.sh
Labels: approved, cla: yes, lgtm, size/XL

#114 Add support for overriding cluster-local-gateway
  config/crds/serving_v1alpha1_knativeserving_crd.yaml
  pkg/apis/serving/v1alpha1/knativeserving_types.go
  pkg/apis/serving/v1alpha1/zz_generated.deepcopy.go
  pkg/reconciler/knativeserving/common/gateway.go
  pkg/reconciler/knativeserving/common/gateway_test.go
Labels: approved, cla: yes, lgtm, size/M

#117 Refactor applying the resources to a helper function.
  pkg/reconciler/knativeserving/knativeserving_controller.go
Labels: approved, cla: yes, lgtm, size/M

#118 Fix spelling errors
  pkg/reconciler/knativeserving/knativeserving_controller.go
Labels: approved, cla: yes, lgtm, ok-to-test, size/XS

#120 Remove auto-install of KS custom resource, fixes #119
  README.md
  cmd/manager/kodata/serving_v1alpha1_knativeserving_cr.yaml
  config/crds/serving_v1alpha1_knativeserving_cr.yaml
  pkg/reconciler/knativeserving/knativeserving_controller.go
  test/e2e-common.sh
  test/e2e/knativeserving_test.go
  test/e2e/knativeservingdeployment_test.go
Labels: approved, cla: yes, lgtm, size/L

#126 Format markdown
  README.md
Labels: approved, cla: yes, lgtm, ok-to-test, size/S

#108 Add test cases to verify the creation of KnativeServing 🧗‍♂️
  test/README.md
  test/cleanup.go
  test/clients.go
  test/crd.go
  test/e2e/knativeservingdeployment_test.go
  test/e2e_flags.go
  test/resources/knativeserving.go
Labels: approved, cla: yes, lgtm, size/L

#127 Remove openshift specific code.
  Gopkg.lock
  config/resources/maistra/maistra-controlplane-0.10.0.yaml
  config/resources/maistra/maistra-operator-0.10.yaml
  config/resources/openshift-ingress/openshift-ingress-0.0.4.yaml
  pkg/reconciler/knativeserving/add_openshift.go
  pkg/reconciler/knativeserving/openshift/openshift.go
  vendor/github.com/openshift/api/LICENSE
  vendor/github.com/openshift/api/config/v1/doc.go
  vendor/github.com/openshift/api/config/v1/register.go
  vendor/github.com/openshift/api/config/v1/stringsource.go
  vendor/github.com/openshift/api/config/v1/types.go
  vendor/github.com/openshift/api/config/v1/types_apiserver.go
  vendor/github.com/openshift/api/config/v1/types_authentication.go
  vendor/github.com/openshift/api/config/v1/types_build.go
  vendor/github.com/openshift/api/config/v1/types_cluster_operator.go
  vendor/github.com/openshift/api/config/v1/types_cluster_version.go
  vendor/github.com/openshift/api/config/v1/types_console.go
  vendor/github.com/openshift/api/config/v1/types_dns.go
  vendor/github.com/openshift/api/config/v1/types_feature.go
  vendor/github.com/openshift/api/config/v1/types_image.go
  vendor/github.com/openshift/api/config/v1/types_infrastructure.go
  vendor/github.com/openshift/api/config/v1/types_ingress.go
  vendor/github.com/openshift/api/config/v1/types_network.go
  vendor/github.com/openshift/api/config/v1/types_oauth.go
  vendor/github.com/openshift/api/config/v1/types_project.go
  vendor/github.com/openshift/api/config/v1/types_proxy.go
  vendor/github.com/openshift/api/config/v1/types_scheduling.go
  vendor/github.com/openshift/api/config/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/config/v1/zz_generated.swagger_doc_generated.go
Labels: approved, cla: yes, lgtm, size/XXL

#112 Simplify extension logic in anticipation of ripping it out entirely
  pkg/reconciler/knativeserving/common/extensions.go
  pkg/reconciler/knativeserving/knativeserving_controller.go
  pkg/reconciler/knativeserving/minikube/minikube.go
Labels: approved, cla: yes, lgtm, size/L

#133 Remove 'scheme'.
  pkg/reconciler/knativeserving/common/extensions.go
  pkg/reconciler/knativeserving/common/gateway.go
  pkg/reconciler/knativeserving/common/gateway_test.go
  pkg/reconciler/knativeserving/common/images.go
  pkg/reconciler/knativeserving/common/images_test.go
  pkg/reconciler/knativeserving/knativeserving_controller.go
Labels: approved, cla: yes, lgtm, size/M

#135 Format markdown
  test/README.md
Labels: approved, cla: yes, lgtm, ok-to-test, size/S

#134 golang format tools
  test/resources/knativeserving.go
Labels: approved, cla: yes, lgtm, ok-to-test, size/XS

#137 Speed up the tests by only deleting one deployment
  test/e2e/knativeservingdeployment_test.go
Labels: approved, cla: yes, lgtm, size/M

#77 Change the branch from master to client-go for dependency jcrossley3/manifestival 🧗‍♂️
  Gopkg.lock
  Gopkg.toml
  pkg/reconciler/knativeserving/knativeserving_controller.go
  vendor/cloud.google.com/go/internal/version/version.go
  vendor/cloud.google.com/go/monitoring/apiv3/doc.go
  vendor/cloud.google.com/go/monitoring/apiv3/notification_channel_client.go
  vendor/cloud.google.com/go/trace/apiv2/doc.go
  vendor/contrib.go.opencensus.io/exporter/stackdriver/resource.go
  vendor/github.com/aws/aws-sdk-go/aws/ec2metadata/service.go
  vendor/github.com/aws/aws-sdk-go/aws/endpoints/defaults.go
  vendor/github.com/aws/aws-sdk-go/aws/endpoints/endpoints.go
  vendor/github.com/aws/aws-sdk-go/aws/endpoints/v3model.go
  vendor/github.com/aws/aws-sdk-go/aws/session/credentials.go
  vendor/github.com/aws/aws-sdk-go/aws/session/doc.go
  vendor/github.com/aws/aws-sdk-go/aws/session/session.go
  vendor/github.com/aws/aws-sdk-go/aws/version.go
  vendor/github.com/aws/aws-sdk-go/service/sts/api.go
  vendor/github.com/jcrossley3/manifestival/manifestival.go
  vendor/github.com/jcrossley3/manifestival/yaml.go
  vendor/golang.org/x/sys/windows/service.go
  vendor/golang.org/x/tools/go/internal/packagesdriver/sizes.go
  vendor/golang.org/x/tools/go/packages/golist.go
  vendor/golang.org/x/tools/go/packages/golist_overlay.go
  vendor/k8s.io/klog/klog.go
  vendor/knative.dev/pkg/Gopkg.lock
  vendor/knative.dev/pkg/apis/v1alpha1/destination.go
  vendor/knative.dev/pkg/apis/v1alpha1/doc.go
  vendor/knative.dev/pkg/kmeta/names.go
  vendor/knative.dev/pkg/test/request.go
  vendor/knative.dev/pkg/test/webhook-apicoverage/coveragecalculator/README.md
  vendor/knative.dev/pkg/test/webhook-apicoverage/coveragecalculator/calculator.go
  vendor/knative.dev/pkg/test/webhook-apicoverage/coveragecalculator/coveragedata.go
  vendor/knative.dev/pkg/test/webhook-apicoverage/coveragecalculator/ignorefields.go
  vendor/knative.dev/pkg/test/webhook-apicoverage/resourcetree/README.md
  vendor/knative.dev/pkg/test/webhook-apicoverage/resourcetree/arraykindnode.go
  vendor/knative.dev/pkg/test/webhook-apicoverage/resourcetree/basictypekindnode.go
  vendor/knative.dev/pkg/test/webhook-apicoverage/resourcetree/node.go
  vendor/knative.dev/pkg/test/webhook-apicoverage/resourcetree/otherkindnode.go
  vendor/knative.dev/pkg/test/webhook-apicoverage/resourcetree/ptrkindnode.go
  vendor/knative.dev/pkg/test/webhook-apicoverage/resourcetree/resourceforest.go
  vendor/knative.dev/pkg/test/webhook-apicoverage/resourcetree/resourcetree.go
  vendor/knative.dev/pkg/test/webhook-apicoverage/resourcetree/rule.go
  vendor/knative.dev/pkg/test/webhook-apicoverage/resourcetree/structkindnode.go
  vendor/knative.dev/pkg/test/webhook-apicoverage/resourcetree/test_util.go
  vendor/knative.dev/pkg/test/webhook-apicoverage/resourcetree/timetypenode.go
  vendor/knative.dev/pkg/test/webhook-apicoverage/tools/README.md
  vendor/knative.dev/pkg/test/webhook-apicoverage/tools/tools.go
  vendor/knative.dev/pkg/test/webhook-apicoverage/view/README.md
  vendor/knative.dev/pkg/test/webhook-apicoverage/view/html_display.go
  vendor/knative.dev/pkg/test/webhook-apicoverage/view/rule.go
  vendor/knative.dev/pkg/test/webhook-apicoverage/webhook/README.md
  vendor/knative.dev/pkg/test/webhook-apicoverage/webhook/apicoverage_recorder.go
  vendor/knative.dev/pkg/test/webhook-apicoverage/webhook/webhook.go
Labels: approved, cla: yes, lgtm, size/XXL

#140 golang format tools
  pkg/reconciler/knativeserving/knativeserving_controller.go
Labels: approved, cla: yes, lgtm, ok-to-test, size/XS

#125 serving operator crashed during startup because connection to api server is not ready
  config/operator.yaml
Labels: approved, cla: yes, lgtm, ok-to-test, size/XS

#141 Remove unused MarkIgnored lifecycle function
  pkg/apis/serving/v1alpha1/knativeserving_lifecycle.go
Labels: approved, cla: yes, lgtm, size/XS

#132 Remove clients of controller-runtime except InjectClient func 🧗‍♂️
  Gopkg.lock
  pkg/reconciler/knativeserving/knativeserving_controller.go
  vendor/github.com/aws/aws-sdk-go/aws/endpoints/defaults.go
  vendor/github.com/aws/aws-sdk-go/aws/version.go
Labels: approved, cla: yes, lgtm, size/M

#143 Update knative serving to 0.8.0
  cmd/manager/kodata/knative-serving/0.8.0.yaml
  version/version.go
Labels: approved, cla: yes, lgtm, size/XL

#144 update the Readme to install knative-serving into the knative-serving…
  README.md
Labels: approved, cla: yes, lgtm, size/S

#128 Drop the dependency on operator-sdk 🧗‍♂️
  Gopkg.lock
  Gopkg.toml
  cmd/manager/main.go
  pkg/reconciler/knativeserving/knativeserving_controller.go
  vendor/github.com/operator-framework/operator-sdk/pkg/predicate/predicate.go
Labels: approved, cla: yes, lgtm, size/M

#149 Update manifestival to accept a logr.Logger
  Gopkg.lock
  pkg/reconciler/knativeserving/knativeserving_controller.go
  vendor/github.com/jcrossley3/manifestival/manifestival.go
Labels: approved, cla: yes, lgtm, size/S

#151 Add the verification of cluster-scoped resource deletion
  Gopkg.lock
  test/clients.go
  test/config/0.8.0.yaml
  test/e2e/knativeservingdeployment_test.go
Labels: approved, cla: yes, lgtm, size/M

#155 golang format tools
  test/e2e/knativeservingdeployment_test.go
Labels: approved, cla: yes, lgtm, ok-to-test, size/XS
