Repository knative/serving-operator, pull requests merged in 2020-03, with the labels that each got.

#315 Add an `--upgrade` flag to `./hack/update-deps.sh`
  hack/update-deps.sh
Labels: approved, cla: yes, lgtm, size/S

#300 Run the upgrade and downgrade tests in the upgrade prow job
  test/README.md
  test/e2e-common.sh
  test/e2e-tests.sh
  test/e2e-upgrade-tests.sh
  test/e2e_flags.go
  test/resources/knativeserving.go
  test/resources/verify.go
  test/upgrade/servingoperator_postupgrade_test.go
  test/upload-test-images.sh
Labels: approved, cla: yes, lgtm, size/L

#316 Auto-update dependencies
  Gopkg.lock
  pkg/apis/serving/v1alpha1/zz_generated.deepcopy.go
  pkg/client/clientset/versioned/clientset.go
  pkg/client/clientset/versioned/doc.go
  pkg/client/clientset/versioned/fake/clientset_generated.go
  pkg/client/clientset/versioned/fake/doc.go
  pkg/client/clientset/versioned/fake/register.go
  pkg/client/clientset/versioned/scheme/doc.go
  pkg/client/clientset/versioned/scheme/register.go
  pkg/client/clientset/versioned/typed/serving/v1alpha1/doc.go
  pkg/client/clientset/versioned/typed/serving/v1alpha1/fake/doc.go
  pkg/client/clientset/versioned/typed/serving/v1alpha1/fake/fake_knativeserving.go
  pkg/client/clientset/versioned/typed/serving/v1alpha1/fake/fake_serving_client.go
  pkg/client/clientset/versioned/typed/serving/v1alpha1/generated_expansion.go
  pkg/client/clientset/versioned/typed/serving/v1alpha1/knativeserving.go
  pkg/client/clientset/versioned/typed/serving/v1alpha1/serving_client.go
  pkg/client/informers/externalversions/factory.go
  pkg/client/informers/externalversions/generic.go
  pkg/client/informers/externalversions/internalinterfaces/factory_interfaces.go
  pkg/client/informers/externalversions/serving/interface.go
  pkg/client/informers/externalversions/serving/v1alpha1/interface.go
  pkg/client/informers/externalversions/serving/v1alpha1/knativeserving.go
  pkg/client/injection/client/client.go
  pkg/client/injection/client/fake/fake.go
  pkg/client/injection/informers/factory/factory.go
  pkg/client/injection/informers/factory/fake/fake.go
  pkg/client/injection/informers/serving/v1alpha1/knativeserving/fake/fake.go
  pkg/client/injection/informers/serving/v1alpha1/knativeserving/knativeserving.go
  pkg/client/listers/serving/v1alpha1/expansion_generated.go
  pkg/client/listers/serving/v1alpha1/knativeserving.go
  vendor/knative.dev/test-infra/scripts/README.md
  vendor/knative.dev/test-infra/scripts/e2e-tests.sh
  vendor/knative.dev/test-infra/scripts/library.sh
  vendor/knative.dev/test-infra/scripts/presubmit-tests.sh
  vendor/knative.dev/test-infra/scripts/release.sh
Labels: approved, cla: yes, lgtm, size/L

#318 golang format tools
  test/resources/knativeserving.go
Labels: approved, cla: yes, lgtm, size/XS

#324 Remove myself from approvers/reviewers
  OWNERS
Labels: approved, cla: yes, lgtm, size/XS

#327 Update the version of Istio to 1.4-latest
  test/e2e-common.sh
Labels: approved, cla: yes, lgtm, size/S

#325 Auto-update dependencies
  Gopkg.lock
  pkg/client/injection/client/client.go
  pkg/client/injection/client/fake/fake.go
  pkg/client/injection/informers/factory/factory.go
  pkg/client/injection/informers/factory/fake/fake.go
  pkg/client/injection/informers/serving/v1alpha1/knativeserving/fake/fake.go
  pkg/client/injection/informers/serving/v1alpha1/knativeserving/knativeserving.go
  vendor/knative.dev/test-infra/scripts/README.md
  vendor/knative.dev/test-infra/scripts/library.sh
  vendor/knative.dev/test-infra/scripts/markdown-link-check-config.rc
  vendor/knative.dev/test-infra/scripts/presubmit-tests.sh
Labels: approved, cla: yes, lgtm, size/M

#328 Auto-update dependencies
  Gopkg.lock
  vendor/knative.dev/pkg/injection/sharedmain/main.go
  vendor/knative.dev/test-infra/scripts/README.md
  vendor/knative.dev/test-infra/scripts/library.sh
  vendor/knative.dev/test-infra/scripts/presubmit-tests.sh
Labels: approved, cla: yes, lgtm, size/M

#326 Remove empty leader election config
  config/config-leader-election.yaml
Labels: approved, cla: yes, lgtm, size/M

#330 Use ko's strict mode for better errors messages
  config/operator.yaml
  hack/generate-yamls.sh
Labels: approved, cla: yes, lgtm, size/XS

#331 Fix prometheus metric nams
  Gopkg.lock
  vendor/knative.dev/pkg/metrics/exporter.go
Labels: approved, cla: yes, lgtm, size/XS

#332 Switch example images to strict mode
  minikube-operator-example/config/operator.yaml
Labels: approved, cla: yes, lgtm, size/XS

#323 Remove includeOutboundIPRanges config from minikube
  minikube-operator-example/cmd/manager/main.go
  minikube-operator-example/cmd/manager/platform.go
Labels: approved, cla: yes, lgtm, size/M

#342 Quick fix for upgrade prow job
  test/e2e-common.sh
  test/e2e-upgrade-tests.sh
Labels: approved, cla: yes, lgtm, size/S

#338 Bump to manifestival 0.4.0
  Gopkg.lock
  Gopkg.toml
  pkg/reconciler/knativeserving/knativeserving_controller.go
  test/resources/verify.go
  vendor/github.com/manifestival/manifestival/client.go
  vendor/github.com/manifestival/manifestival/dry.go
  vendor/github.com/manifestival/manifestival/filter.go
  vendor/github.com/manifestival/manifestival/manifestival.go
  vendor/github.com/manifestival/manifestival/patch/patch.go
  vendor/github.com/manifestival/manifestival/transform.go
Labels: approved, cla: yes, lgtm, size/L

#339 Auto-update dependencies
  Gopkg.lock
  vendor/knative.dev/test-infra/scripts/release.sh
Labels: approved, cla: yes, lgtm, size/S

#337 Add support for HA control plane
  Gopkg.lock
  config/300-serving-v1alpha1-knativeserving-crd.yaml
  pkg/apis/serving/v1alpha1/knativeserving_types.go
  pkg/apis/serving/v1alpha1/zz_generated.deepcopy.go
  pkg/reconciler/knativeserving/common/extensions.go
  pkg/reconciler/knativeserving/common/ha.go
  pkg/reconciler/knativeserving/common/ha_test.go
  pkg/reconciler/knativeserving/common/images.go
Labels: approved, cla: yes, lgtm, size/L

#347 Upgrade to latest `test-infra`
  Gopkg.lock
  vendor/knative.dev/test-infra/scripts/release.sh
Labels: approved, cla: yes, lgtm, size/XS

#348 Upgrade to latest `test-infra`.
  Gopkg.lock
  vendor/knative.dev/test-infra/scripts/release.sh
Labels: approved, cla: yes, lgtm, size/XS

#346 Remove the deprecated short name from README
  README.md
Labels: approved, cla: yes, lgtm, ok-to-test, size/XS

#350 [release-0.13]Update test-infra for release hotfix
  Gopkg.lock
  vendor/knative.dev/test-infra/scripts/release.sh
Labels: approved, cla: yes, lgtm, size/S

#356 Update test-infra for release hotfix
  Gopkg.lock
  test/e2e-upgrade-tests.sh
  vendor/knative.dev/test-infra/scripts/release.sh
Labels: approved, cla: yes, lgtm, size/S

#358 Update the upgrade to check upgrading from 0.13.0
  test/e2e-common.sh
  test/e2e-upgrade-tests.sh
  test/upgrade/servingoperator_postupgrade_test.go
Labels: approved, cla: yes, lgtm, size/S

#359 Delete (Cluster)Role(Bindings) as a final cleanup step.
  pkg/reconciler/knativeserving/knativeserving_controller.go
Labels: approved, cla: yes, lgtm, size/XS

#363 Auto-update dependencies
  Gopkg.lock
  vendor/knative.dev/test-infra/scripts/presubmit-tests.sh
Labels: approved, cla: yes, lgtm, size/S

#365 Abide by first rule of structural schemas
  config/300-serving-v1alpha1-knativeserving-crd.yaml
Labels: approved, cla: yes, lgtm, size/XS

#366 Enable 'kubectl explain knativeserving' to work
  config/300-serving-v1alpha1-knativeserving-crd.yaml
Labels: approved, cla: yes, lgtm, size/XS

#370 Auto-update dependencies
  Gopkg.lock
  vendor/knative.dev/test-infra/scripts/README.md
  vendor/knative.dev/test-infra/scripts/library.sh
  vendor/knative.dev/test-infra/scripts/presubmit-tests.sh
Labels: approved, cla: yes, lgtm, size/M

#371 [release-0.13] Auto-update dependencies
  Gopkg.lock
  vendor/knative.dev/test-infra/scripts/README.md
  vendor/knative.dev/test-infra/scripts/library.sh
  vendor/knative.dev/test-infra/scripts/presubmit-tests.sh
Labels: approved, cla: yes, lgtm, size/M

#368 Update the manifest to 0.13.1
  cmd/manager/kodata/knative-serving/0.13.1.yaml
  version/version.go
Labels: approved, cla: yes, lgtm, size/XXL

#369 Update the manifest to the latest nightly build
  cmd/manager/kodata/knative-serving/serving.yaml
  version/version.go
Labels: approved, cla: yes, lgtm, size/XXL

#372 Print log message when start deleting resources
  pkg/reconciler/knativeserving/knativeserving_controller.go
Labels: approved, cla: yes, lgtm, size/XS

#362 Resources override
  Gopkg.lock
  config/300-serving-v1alpha1-knativeserving-crd.yaml
  pkg/apis/serving/v1alpha1/knativeserving_types.go
  pkg/apis/serving/v1alpha1/zz_generated.deepcopy.go
  pkg/reconciler/knativeserving/common/extensions.go
  pkg/reconciler/knativeserving/common/resources.go
  pkg/reconciler/knativeserving/common/resources_test.go
  pkg/reconciler/knativeserving/common/testdata/manifest.yaml
Labels: approved, cla: yes, lgtm, size/XXL

#376 [release-0.13] Auto-update dependencies
  Gopkg.lock
  vendor/knative.dev/test-infra/scripts/library.sh
Labels: approved, cla: yes, lgtm, size/S

#375 Add Cynocracy to reviewers.
  OWNERS
Labels: approved, cla: yes, lgtm, size/XS

#377 [master] Auto-update dependencies
  Gopkg.lock
  vendor/knative.dev/test-infra/scripts/library.sh
Labels: approved, cla: yes, lgtm, size/S

#374 Install from the manifest in a strict(er) order.
  pkg/reconciler/knativeserving/knativeserving_controller.go
Labels: approved, cla: yes, lgtm, size/S

#373 k4leung4 steps down as approver/reviewer
  OWNERS
Labels: approved, cla: yes, lgtm, size/XS

#379 Update release with 0.13.2 serving
  cmd/manager/kodata/knative-serving/0.13.2.yaml
  version/version.go
Labels: approved, cla: yes, lgtm, size/XXL

#291 Restrict RBAC for Operator
  config/role.yaml
  config/role_binding.yaml
Labels: approved, cla: yes, lgtm, size/L
