Repository knative/serving-operator, pull requests merged in 2020-01, with the labels that each got.

#249 Drop knative.dev/serving as dependency
  Gopkg.lock
  pkg/reconciler/reconciler_test.go
  vendor/knative.dev/serving/AUTHORS
  vendor/knative.dev/serving/LICENSE
  vendor/knative.dev/serving/cmd/activator/kodata/LICENSE
  vendor/knative.dev/serving/cmd/autoscaler-hpa/kodata/LICENSE
  vendor/knative.dev/serving/cmd/autoscaler/kodata/LICENSE
  vendor/knative.dev/serving/cmd/controller/kodata/LICENSE
  vendor/knative.dev/serving/cmd/networking/certmanager/kodata/LICENSE
  vendor/knative.dev/serving/cmd/networking/istio/kodata/LICENSE
  vendor/knative.dev/serving/cmd/networking/nscert/kodata/LICENSE
  vendor/knative.dev/serving/cmd/queue/kodata/LICENSE
  vendor/knative.dev/serving/cmd/webhook/kodata/LICENSE
  vendor/knative.dev/serving/pkg/client/istio/clientset/versioned/clientset.go
  vendor/knative.dev/serving/pkg/client/istio/clientset/versioned/doc.go
  vendor/knative.dev/serving/pkg/client/istio/clientset/versioned/fake/clientset_generated.go
  vendor/knative.dev/serving/pkg/client/istio/clientset/versioned/fake/doc.go
  vendor/knative.dev/serving/pkg/client/istio/clientset/versioned/fake/register.go
  vendor/knative.dev/serving/pkg/client/istio/clientset/versioned/scheme/doc.go
  vendor/knative.dev/serving/pkg/client/istio/clientset/versioned/scheme/register.go
  vendor/knative.dev/serving/pkg/client/istio/clientset/versioned/typed/networking/v1alpha3/destinationrule.go
  vendor/knative.dev/serving/pkg/client/istio/clientset/versioned/typed/networking/v1alpha3/doc.go
  vendor/knative.dev/serving/pkg/client/istio/clientset/versioned/typed/networking/v1alpha3/envoyfilter.go
  vendor/knative.dev/serving/pkg/client/istio/clientset/versioned/typed/networking/v1alpha3/fake/doc.go
  vendor/knative.dev/serving/pkg/client/istio/clientset/versioned/typed/networking/v1alpha3/fake/fake_destinationrule.go
  vendor/knative.dev/serving/pkg/client/istio/clientset/versioned/typed/networking/v1alpha3/fake/fake_envoyfilter.go
  vendor/knative.dev/serving/pkg/client/istio/clientset/versioned/typed/networking/v1alpha3/fake/fake_gateway.go
  vendor/knative.dev/serving/pkg/client/istio/clientset/versioned/typed/networking/v1alpha3/fake/fake_networking_client.go
  vendor/knative.dev/serving/pkg/client/istio/clientset/versioned/typed/networking/v1alpha3/fake/fake_serviceentry.go
  vendor/knative.dev/serving/pkg/client/istio/clientset/versioned/typed/networking/v1alpha3/fake/fake_sidecar.go
  vendor/knative.dev/serving/pkg/client/istio/clientset/versioned/typed/networking/v1alpha3/fake/fake_virtualservice.go
  vendor/knative.dev/serving/pkg/client/istio/clientset/versioned/typed/networking/v1alpha3/gateway.go
  vendor/knative.dev/serving/pkg/client/istio/clientset/versioned/typed/networking/v1alpha3/generated_expansion.go
  vendor/knative.dev/serving/pkg/client/istio/clientset/versioned/typed/networking/v1alpha3/networking_client.go
  vendor/knative.dev/serving/pkg/client/istio/clientset/versioned/typed/networking/v1alpha3/serviceentry.go
  vendor/knative.dev/serving/pkg/client/istio/clientset/versioned/typed/networking/v1alpha3/sidecar.go
  vendor/knative.dev/serving/pkg/client/istio/clientset/versioned/typed/networking/v1alpha3/virtualservice.go
  vendor/knative.dev/serving/pkg/client/istio/injection/client/client.go
  vendor/knative.dev/serving/pkg/client/istio/injection/client/fake/fake.go
  vendor/knative.dev/serving/third_party/config/monitoring/logging/elasticsearch/LICENSE
  vendor/knative.dev/serving/third_party/config/monitoring/metrics/prometheus/kubernetes/LICENSE
  vendor/knative.dev/serving/third_party/config/monitoring/metrics/prometheus/prometheus-operator/LICENSE
  vendor/knative.dev/serving/third_party/config/monitoring/metrics/prometheus/prometheus-operator/NOTICE
Labels: approved, cla: yes, lgtm, ok-to-test, size/XXL

#250 Remove the short name for consistent decision in Operation WG
  config/300-serving-v1alpha1-knativeserving-crd.yaml
Labels: approved, cla: yes, lgtm, size/XS

#252 Update the released YAML to 0.11.1 for Knative Serving
  cmd/manager/kodata/knative-serving/0.11.1.yaml
  version/version.go
Labels: approved, cla: yes, lgtm, size/L

#254 Update the year of the copyright to 2020 in the template
  hack/boilerplate/boilerplate.go.txt
Labels: approved, cla: yes, lgtm, size/XS

#259 Add badges to readme
  README.md
Labels: approved, cla: yes, lgtm, size/XS

#263 OLM metadata
  .gitignore
  README.md
  deploy/olm-catalog/knative-serving-operator/0.11.0/knative-serving-operator.v0.11.0.clusterserviceversion.yaml
  deploy/olm-catalog/knative-serving-operator/0.11.0/knativeservings.operator.knative.dev.crd.yaml
  deploy/olm-catalog/knative-serving-operator/knative-serving-operator.package.yaml
  hack/generate-olm-catalog-source.sh
Labels: approved, cla: yes, lgtm, ok-to-test, size/L

#255 Add the template for Knative projects
  .github/ISSUE_TEMPLATE/bug-report.md
  .github/ISSUE_TEMPLATE/feature-request.md
  .github/issue-template.md
Labels: approved, cla: yes, lgtm, size/M

#265 Add the instruction on how to upgrade v0.10 and v0.11 to v0.12
  README.md
  doc/upgrade_guide.md
Labels: approved, cla: yes, lgtm, size/M

#266 Format markdown
  README.md
  doc/upgrade_guide.md
Labels: approved, cla: yes, lgtm, size/S

#267 OLM metadata for 0.12.0
  deploy/olm-catalog/knative-serving-operator/0.12.0/300-serving-v1alpha1-knativeserving-crd.yaml
  deploy/olm-catalog/knative-serving-operator/0.12.0/knative-serving-operator.v0.12.0.clusterserviceversion.yaml
  deploy/olm-catalog/knative-serving-operator/knative-serving-operator.package.yaml
Labels: approved, cla: yes, lgtm, ok-to-test, size/L

#268 Print error in knativeServingDelete
  test/e2e/knativeservingdeployment_test.go
Labels: approved, cla: yes, lgtm, size/XS

#270 Remove obsolete .travis.yaml.
  .travis.yml
Labels: approved, cla: yes, lgtm, size/S

#272 Update the manifest of Knative Serving from 0.12.0 to 0.12.1
  cmd/manager/kodata/knative-serving/0.12.1.yaml
  version/version.go
Labels: approved, cla: yes, lgtm, size/L

#273 Update the manifest of Knative Serving from 0.12.0 to 0.12.1 (#272)
  cmd/manager/kodata/knative-serving/0.12.1.yaml
  version/version.go
Labels: approved, cla: yes, lgtm, size/L

#269 Fix OLM metadata for 0.11.0
  deploy/olm-catalog/knative-serving-operator/0.11.0/knative-serving-operator.v0.11.0.clusterserviceversion.yaml
Labels: approved, cla: yes, lgtm, ok-to-test, size/XS
