Repository knative/serving-operator, pull requests merged in 2020-04, with the labels that each got.

#387 Fix the retry issue with deployment verification
  test/resources/knativeserving.go
  test/resources/verify.go
Labels: approved, cla: yes, lgtm, size/S

#390 [master] Auto-update dependencies
  Gopkg.lock
  vendor/knative.dev/pkg/Gopkg.lock
  vendor/knative.dev/pkg/Gopkg.toml
  vendor/knative.dev/pkg/injection/sharedmain/main.go
  vendor/knative.dev/pkg/leaderelection/config.go
  vendor/knative.dev/pkg/test/helpers/dir.go
  vendor/knative.dev/pkg/test/performance/performance.go
  vendor/knative.dev/pkg/test/testgrid/testgrid.go
  vendor/knative.dev/pkg/webhook/admission.go
  vendor/knative.dev/pkg/webhook/configmaps/configmaps.go
  vendor/knative.dev/pkg/webhook/resourcesemantics/defaulting/defaulting.go
  vendor/knative.dev/pkg/webhook/resourcesemantics/validation/validation.go
  vendor/knative.dev/pkg/webhook/webhook.go
  vendor/knative.dev/test-infra/scripts/e2e-tests.sh
  vendor/knative.dev/test-infra/scripts/presubmit-tests.sh
Labels: approved, cla: yes, lgtm, size/L

#392 [master] Auto-update dependencies
  Gopkg.lock
  vendor/knative.dev/pkg/apis/condition_set.go
  vendor/knative.dev/pkg/injection/sharedmain/main.go
  vendor/knative.dev/pkg/metrics/config.go
  vendor/knative.dev/pkg/metrics/config_observability.go
  vendor/knative.dev/pkg/metrics/exporter.go
  vendor/knative.dev/pkg/testutils/clustermanager/e2e-tests/config.go
  vendor/knative.dev/pkg/testutils/clustermanager/e2e-tests/gke.go
  vendor/knative.dev/pkg/testutils/clustermanager/e2e-tests/util.go
  vendor/knative.dev/pkg/testutils/clustermanager/prow-cluster-operation/actions/create.go
  vendor/knative.dev/pkg/testutils/clustermanager/prow-cluster-operation/actions/delete.go
  vendor/knative.dev/pkg/testutils/metahelper/client/client.go
  vendor/knative.dev/pkg/testutils/metahelper/main.go
Labels: approved, cla: yes, lgtm, size/L

#389 Add aliok as one approver of knative operator
  OWNERS
Labels: approved, cla: yes, lgtm, size/XS

#394 Respect HA Replicas setting in HPAs.
  pkg/reconciler/knativeserving/common/ha.go
  pkg/reconciler/knativeserving/common/ha_test.go
Labels: approved, cla: yes, lgtm, size/M

#380 Use Genreconciler for KnativeServing
  Gopkg.lock
  pkg/apis/serving/v1alpha1/knativeserving_lifecycle.go
  pkg/apis/serving/v1alpha1/knativeserving_types.go
  pkg/apis/serving/v1alpha1/zz_generated.deepcopy.go
  pkg/client/injection/reconciler/serving/v1alpha1/knativeserving/controller.go
  pkg/client/injection/reconciler/serving/v1alpha1/knativeserving/reconciler.go
  pkg/client/injection/reconciler/serving/v1alpha1/knativeserving/stub/controller.go
  pkg/client/injection/reconciler/serving/v1alpha1/knativeserving/stub/reconciler.go
  pkg/reconciler/knativeserving/controller.go
  pkg/reconciler/knativeserving/knativeserving.go
  pkg/reconciler/reconciler.go
  pkg/reconciler/reconciler_test.go
  third_party/VENDOR-LICENSE
  vendor/gomodules.xyz/jsonpatch/LICENSE
  vendor/gomodules.xyz/jsonpatch/v2/jsonpatch.go
Labels: approved, cla: yes, lgtm, size/XXL

#396 Update the manifest to the nightly built version
  cmd/manager/kodata/knative-serving/serving.yaml
  version/version.go
Labels: approved, cla: yes, lgtm, size/XXL

#401 Allow Operator to use Jobs as part of upgrades.
  config/role.yaml
Labels: approved, cla: yes, lgtm, size/S

#402 Also allow job updates.
  config/role.yaml
Labels: approved, cla: yes, lgtm, size/XS

#403 Update the manifest of serving to 0.14.0
  Gopkg.lock
  Gopkg.toml
  cmd/manager/kodata/knative-serving/1-serving-crds.yaml
  cmd/manager/kodata/knative-serving/2-serving-core.yaml
  cmd/manager/kodata/knative-serving/3-serving-hpa.yaml
  cmd/manager/kodata/knative-serving/4-net-istio.yaml
  test/e2e-common.sh
  vendor/knative.dev/pkg/Gopkg.lock
  vendor/knative.dev/pkg/Gopkg.toml
  vendor/knative.dev/pkg/apiextensions/storageversion/cmd/migrate/config.go
  vendor/knative.dev/pkg/apiextensions/storageversion/cmd/migrate/main.go
  vendor/knative.dev/pkg/apiextensions/storageversion/migrator.go
  vendor/knative.dev/pkg/apis/contexts.go
  vendor/knative.dev/pkg/apis/duck/ABOUT.md
  vendor/knative.dev/pkg/apis/duck/images/Knative-Duck0.png
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/packages.go
  vendor/knative.dev/pkg/leaderelection/config.go
  vendor/knative.dev/pkg/metrics/monitored_resources.go
  vendor/knative.dev/pkg/resolver/addressable_resolver.go
  vendor/knative.dev/pkg/test/cmd/command.go
  vendor/knative.dev/pkg/test/e2e_flags.go
  vendor/knative.dev/pkg/test/logging/sugar.go
  vendor/knative.dev/pkg/test/logging/tlogger.go
  vendor/knative.dev/pkg/test/testgrid/testgrid.go
  vendor/knative.dev/pkg/testing/resource.go
  vendor/knative.dev/pkg/testutils/clustermanager/e2e-tests/gke.go
  vendor/knative.dev/pkg/testutils/clustermanager/e2e-tests/setup.go
  vendor/knative.dev/pkg/testutils/clustermanager/e2e-tests/util.go
  vendor/knative.dev/pkg/testutils/clustermanager/prow-cluster-operation/options/options.go
  vendor/knative.dev/pkg/tracker/enqueue.go
  vendor/knative.dev/pkg/webhook/resourcesemantics/conversion/conversion.go
  vendor/knative.dev/pkg/webhook/resourcesemantics/validation/controller.go
  vendor/knative.dev/pkg/webhook/resourcesemantics/validation/reconcile_config.go
  vendor/knative.dev/pkg/webhook/resourcesemantics/validation/validation_admit.go
  vendor/knative.dev/pkg/webhook/testing/testing.go
  vendor/knative.dev/pkg/webhook/webhook.go
  vendor/knative.dev/test-infra/tools/dep-collector/gobuild.go
  vendor/knative.dev/test-infra/tools/dep-collector/imports.go
  vendor/knative.dev/test-infra/tools/dep-collector/licenses.go
  version/version.go
Labels: approved, cla: yes, lgtm, size/XXL

#407 Pass config from main to the controller.
  cmd/manager/main.go
  minikube-operator-example/cmd/manager/main.go
  pkg/reconciler/knativeserving/controller.go
Labels: approved, cla: yes, lgtm, size/L

#360 OLM metadata for 0.13.1
  deploy/olm-catalog/knative-serving-operator/0.13.1/knative-serving-operator.v0.13.1.clusterserviceversion.yaml
  deploy/olm-catalog/knative-serving-operator/0.13.1/knativeservings.operator.knative.dev.crd.yaml
  deploy/olm-catalog/knative-serving-operator/knative-serving-operator.package.yaml
Labels: approved, cla: yes, lgtm, size/L
