Repository knative/serving-operator, pull requests merged in 2020-02, with the labels that each got.

#284 Add a comment about why cluster-admin is necessary.
  config/role.yaml
Labels: approved, cla: yes, lgtm, size/XS

#285 Remove greghaynes, whom left
  OWNERS
Labels: approved, cla: yes, lgtm, size/XS

#281 Add image override logic for DaemonSet
  pkg/reconciler/knativeserving/common/certs_test.go
  pkg/reconciler/knativeserving/common/extensions.go
  pkg/reconciler/knativeserving/common/images.go
  pkg/reconciler/knativeserving/common/images_test.go
Labels: approved, cla: yes, lgtm, size/L

#288 Pull in manifestival fix for #283 from @houshengbo
  Gopkg.lock
  vendor/github.com/jcrossley3/manifestival/transform.go
Labels: approved, cla: yes, lgtm, size/S

#289 Rename e2e-tests-latest-serving.sh into e2e-upgrade-tests
  test/e2e-upgrade-tests.sh
  test/presubmit-tests.sh
Labels: approved, cla: yes, lgtm, size/S

#286 Add upgrade tests into the e2e-tests-latest-serving
  test/client/setup.go
  test/e2e-common.sh
  test/e2e-tests.sh
  test/e2e-upgrade-tests.sh
  test/e2e/knativeservingdeployment_test.go
  test/resources/knativeserving.go
  test/resources/verify.go
  test/upgrade/servingoperator_postupgrade_test.go
Labels: approved, cla: yes, lgtm, size/XL, upgrade

#290 Move manifestival to its own org
  Gopkg.lock
  Gopkg.toml
  pkg/reconciler/knativeserving/common/certs.go
  pkg/reconciler/knativeserving/common/config_maps.go
  pkg/reconciler/knativeserving/common/extensions.go
  pkg/reconciler/knativeserving/common/gateway.go
  pkg/reconciler/knativeserving/common/images.go
  pkg/reconciler/knativeserving/controller.go
  pkg/reconciler/knativeserving/knativeserving_controller.go
  pkg/reconciler/knativeserving/minikube/minikube.go
  test/resources/verify.go
  third_party/VENDOR-LICENSE
  vendor/github.com/manifestival/manifestival/LICENSE
  vendor/github.com/manifestival/manifestival/manifestival.go
  vendor/github.com/manifestival/manifestival/patch/patch.go
  vendor/github.com/manifestival/manifestival/transform.go
  vendor/github.com/manifestival/manifestival/yaml.go
  version/version_test.go
Labels: approved, cla: yes, lgtm, size/L

#293 Support reading KubeConfig from KUBECONFIG env var
  cmd/manager/main.go
  pkg/reconciler/knativeserving/controller.go
Labels: approved, cla: yes, lgtm, ok-to-test, size/XS

#296 golang format tools
  pkg/reconciler/knativeserving/controller.go
Labels: approved, cla: yes, lgtm, size/XS

#299 Cherry pick for release 0.12 to support KUBECONFIG in OLM
  Gopkg.lock
  Gopkg.toml
  cmd/manager/main.go
  pkg/reconciler/knativeserving/common/certs.go
  pkg/reconciler/knativeserving/common/config_maps.go
  pkg/reconciler/knativeserving/common/extensions.go
  pkg/reconciler/knativeserving/common/gateway.go
  pkg/reconciler/knativeserving/common/images.go
  pkg/reconciler/knativeserving/controller.go
  pkg/reconciler/knativeserving/knativeserving_controller.go
  pkg/reconciler/knativeserving/minikube/minikube.go
  test/client/setup.go
  test/e2e-common.sh
  test/e2e-tests.sh
  test/e2e-upgrade-tests.sh
  test/e2e/knativeservingdeployment_test.go
  test/presubmit-tests.sh
  test/resources/knativeserving.go
  test/resources/verify.go
  test/upgrade/servingoperator_postupgrade_test.go
  third_party/VENDOR-LICENSE
  vendor/github.com/manifestival/manifestival/LICENSE
  vendor/github.com/manifestival/manifestival/manifestival.go
  vendor/github.com/manifestival/manifestival/patch/patch.go
  vendor/github.com/manifestival/manifestival/transform.go
  vendor/github.com/manifestival/manifestival/yaml.go
  version/version_test.go
Labels: approved, cla: yes, lgtm, size/XL

#297 Update to Manifestival v0.1.0
  Gopkg.lock
  Gopkg.toml
  pkg/reconciler/knativeserving/controller.go
  pkg/reconciler/knativeserving/knativeserving_controller.go
  test/resources/verify.go
  third_party/VENDOR-LICENSE
  vendor/github.com/go-logr/logr/testing/null.go
  vendor/github.com/go-logr/logr/testing/test.go
  vendor/github.com/manifestival/client-go-client/LICENSE
  vendor/github.com/manifestival/client-go-client/client.go
  vendor/github.com/manifestival/manifestival/client.go
  vendor/github.com/manifestival/manifestival/manifestival.go
  vendor/github.com/manifestival/manifestival/options.go
  vendor/github.com/manifestival/manifestival/transform.go
  vendor/github.com/operator-framework/operator-sdk/pkg/restmapper/dynamicrestmapper.go
Labels: approved, cla: yes, lgtm, size/XL

#295 Support the platform-specific or custom transformers
  minikube-operator-example/cmd/manager/kodata/knative-serving/0.12.1.yaml
  minikube-operator-example/cmd/manager/main.go
  minikube-operator-example/cmd/manager/platform.go
  minikube-operator-example/config/300-serving-v1alpha1-knativeserving-crd.yaml
  minikube-operator-example/config/config-logging.yaml
  minikube-operator-example/config/config-observability.yaml
  minikube-operator-example/config/operator.yaml
  minikube-operator-example/config/role.yaml
  minikube-operator-example/config/role_binding.yaml
  minikube-operator-example/config/service_account.yaml
  pkg/reconciler/knativeserving/add_minikube.go
  pkg/reconciler/knativeserving/common/extensions.go
  pkg/reconciler/knativeserving/controller.go
  pkg/reconciler/knativeserving/knativeserving_controller.go
Labels: approved, cla: yes, lgtm, size/L

#305 golang format tools
  pkg/reconciler/knativeserving/knativeserving_controller.go
Labels: approved, cla: yes, lgtm, size/XS

#306 Update to manifestival 0.2.0
  Gopkg.lock
  Gopkg.toml
  pkg/reconciler/knativeserving/knativeserving_controller.go
  test/resources/verify.go
  vendor/github.com/manifestival/client-go-client/client.go
  vendor/github.com/manifestival/manifestival/client.go
  vendor/github.com/manifestival/manifestival/filter.go
  vendor/github.com/manifestival/manifestival/manifestival.go
  vendor/github.com/manifestival/manifestival/options.go
  vendor/github.com/manifestival/manifestival/source.go
  vendor/github.com/manifestival/manifestival/sources/path.go
  vendor/github.com/manifestival/manifestival/sources/yaml.go
  vendor/github.com/manifestival/manifestival/transform.go
  version/version_test.go
Labels: approved, cla: yes, lgtm, size/XL

#308 No longer deleting CRD's when KnativeServing is deleted
  pkg/reconciler/knativeserving/knativeserving_controller.go
  test/resources/verify.go
Labels: approved, cla: yes, lgtm, size/S

#311 OLM metadata for 0.12.2
  deploy/olm-catalog/knative-serving-operator/0.12.2/knative-serving-operator.v0.12.2.clusterserviceversion.yaml
  deploy/olm-catalog/knative-serving-operator/0.12.2/knativeservings.operator.knative.dev.crd.yaml
  deploy/olm-catalog/knative-serving-operator/knative-serving-operator.package.yaml
Labels: approved, cla: yes, lgtm, size/L
